In [1]:
import numpy as np

In [2]:
a1 = np.arange(3)

In [5]:
np.exp(a1)  # 自然指数函数 返回的时e的a1元素指数

array([1.        , 2.71828183, 7.3890561 ])

In [8]:
np.sqrt(a1)  # 平方根

array([0.        , 1.        , 1.41421356])

In [15]:
a2 = np.arange(3)

In [18]:
np.add(a1,a2)  # 元素相加

array([0, 2, 4])

In [19]:
a3 = np.array([1.5,1.6,1.7,1.8])

In [28]:
i,j = np.modf(a3)  # 将元素的小数部分和整数部分传给两个对象

In [27]:
i,j

(array([0.5, 0.6, 0.7, 0.8]), array([1., 1., 1., 1.]))

In [29]:
a4 = np.array([[1,4],[6,7]])

In [30]:
a5 = np.array([[2,3],[5,8]])

In [32]:
np.maximum(a4,a5)  # 获取两个数组中各元素中最大的元素

array([[2, 4],
       [6, 8]])

In [33]:
np.minimum(a4,a5)

array([[1, 3],
       [5, 7]])

In [35]:
np.abs(a4)  # 每个元素的绝对值

array([[1, 4],
       [6, 7]])

In [36]:
np.square(a4)  # 每个元素的平方

array([[ 1, 16],
       [36, 49]], dtype=int32)

In [37]:
np.isnan(a4)

array([[False, False],
       [False, False]])